#163294622 signup endpoint_v2
jackiegitari1234/Questioner_v2 pull request #5
Opened 2019-01-20 20:21 UTC by jackiegitari1234

**What does this PR do?**
- Creates an end point for a user to sign-up

**Description of Task to be completed?**
- Create an endpoint that enables a user to create an account at Questioner
- all tests created should pass

**How should this be manually tested?**
- clone the repository to your local machine
- run the commands
 -   `source venv/bin/activate`  to create a virtual environment
 -   `export FLASK_ENV=development` to setup the environment 
 - `flask run`
-  use postman to test the end point

What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/n/projects/2235314
#163054752

*Screenshot*
![rgstr](https://user-images.githubusercontent.com/43432747/51444558-0a3a9280-1d0a-11e9-8e17-afcc218070cb.png)

2019-01-20 20:40 UTC, SolomonMacharia commented
looks nice. You may consider generating hashed passwords for better security.

2019-01-20 21:13 UTC, jackiegitari1234 commented
> looks nice. You may consider generating hashed passwords for better security.

thanks

2019-01-21 03:20 UTC, wangonya commented
Looks good 👍🏾

2019-01-22 07:10 UTC, RuthNjeri commented on .travis.yml
> +  - coveralls
add an empty line after line 12

2019-01-22 07:12 UTC, RuthNjeri requested changes

2019-01-22 07:12 UTC, RuthNjeri commented on app/api/v2/models/Basemodel.py
> +#         execCommand(query)
If you are not using this file you should delete it. A commented code should not be pushed

2019-01-22 07:17 UTC, RuthNjeri commented on app/api/v2/models/auth_model.py
> +            # "public_id": str(uuid.uuid4()),
Do not push commented code.

2019-01-22 07:17 UTC, RuthNjeri commented on app/api/v2/models/auth_model.py
> +            # "public_id": str(uuid.uuid4()),
Do not push commented code.

2019-01-22 07:19 UTC, RuthNjeri commented on app/api/v2/utils/database.py
> +            db_url="dbname='testingdb' host='127.0.0.1' port='5433' user='postgres' password='12345'"
I think you can also create a `TEST_DATABASE_URL` just like how you have created the development `DATABASE_URL` and get it from the env.

2019-01-22 07:47 UTC, RuthNjeri commented
In what you have listed as **How should this be manually tested?**  in the PR details:

1. `source venv/bin/activate` to create a virtual environment - Does not create a virtual environment, it activates it. 
2. You should describe how to create a virtual environment before activating it.
3. You should also specify how to install the dependencies from the `requirements.txt` into the virtual environment.

2019-01-22 08:42 UTC, RuthNjeri commented on Instance/config.py
>      SECRET = os.getenv('SECRET')
You have a `SECRET_KEY` and a `SECRET` from the environment. You should pick one, preferably one that is hidden in the env.

2019-01-22 13:17 UTC, merged